# .github/workflows/firebase-hosting-merge.yml
# This workflow is for deploying to your LIVE Firebase Hosting site (e.g., your-app.web.app)
# It triggers on pushes to the master/main branch.
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master # Ensure this matches your main branch name (e.g., 'main' or 'master')

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run npm run build
        run: npm run build
        env:
          CI: true

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRATEGYCENTRE_WEALTHBOX }}'
          projectId: strategycentre-wealthbox
          # IMPORTANT: Do NOT include 'expires' or 'channelId' here for live site deployment.
          # The action will default to 'firebase deploy' which deploys to the live site.
