# .github/workflows/firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master # or main, depending on your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    # --- IMPORTANT: ADD THIS STEP IF IT'S MISSING ---
    - name: Install dependencies
      run: npm install
    # --- END IMPORTANT ADDITION ---

    - name: Run npm run build
      run: npm run build
      env:
        # If you have environment variables for production build, define them here.
        # Example: CI: true is often used to prevent build warnings from failing CI builds.
        CI: true 

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRATEGYCENTRE_WEALTHBOX }}'
        projectId: strategycentre-wealthbox
        # Live channel is 'live' by default. You can specify a different channel here if needed.