# .github/workflows/firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master # or main, depending on your main branch name (usually 'main' in newer repos)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    # --- IMPORTANT: Install dependencies before building ---
    - name: Install dependencies
      run: npm install
    # --- END IMPORTANT ---

    - name: Run npm run build
      run: npm run build
      env:
        # CI: true is often used in CI/CD to prevent warnings from breaking the build
        CI: true

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRATEGYCENTRE_WEALTHBOX }}'
        projectId: strategycentre-wealthbox
        # The 'expires: 7d' line has been REMOVED from here.
        # This ensures deployment goes to the live site (default channel) for the master/main branch.
