# .github/workflows/firebase-hosting-pull-request.yml
# This file is for deploying preview channels for pull requests.
# It only runs when a pull request is opened, synchronized, or reopened.
name: Deploy Firebase Hosting PR Previews

on: pull_request # This workflow ONLY runs on pull requests

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run npm run build
        run: npm run build
        env:
          CI: true

      - name: Deploy to Firebase Hosting Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRATEGYCENTRE_WEALTHBOX }}'
          projectId: strategycentre-wealthbox
          # When using 'expires', 'channelId' is REQUIRED for hosting:channel:deploy.
          # This uses the pull request's head branch name as the preview channel ID.
          channelId: ${{ github.head_ref }}
          expires: 7d # Preview channel expires after 7 days
